[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Anton Vasiljev <antono.vasiljev@gmail.com>"]

[lib]
name = "utils"
path = "src/utils.rs"

[dependencies]
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"

